### PR TITLE
Update path on facebook sign-in link (Devise deprecation)

### PR DESCRIPTION
**Pull request by michaelsimon**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by pletcher** [comment]
Hi @michaelsimon, could you describe this change a bit more (or point to where Devise has deprecated this)? I'm a little behind on my Devise developments, sorry!

**Comment by pletcher** [comment]
Because I still see 

> Note that devise does not create *_url methods. While you will never use the callback helper above directly, you only need to add the first one to your layouts in order to provide facebook authentication:
> 
> <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

in Devise's docs: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

**Comment by michaelsimon** [comment]
Hi @pletcher when I run rspec/learn with the `user_omniauth_authorize_path(:facebook)` currently on the page, the following prints in my console:

```
DEPRECATION WARNING: [Devise] user_omniauth_authorize_path(:facebook) is deprecated 
and it will be removed from Devise 4.2.

Please use user_facebook_omniauth_authorize_path instead.
 (called from _app_views_layouts_application_html_erb__3943331048231481223_70318611420660 at /Users/mhsimon/Development/code/devise_lab-v-000/app/views/layouts/application.html.erb:13)
```

The gem version of devise that was bundled in my app appears to be 4.1.0 per Gemfile.lock.

**Comment by pletcher** [comment]
Awesome, thanks! Was able to match up your error with [this](https://github.com/plataformatec/devise/pull/3985) -- your fix LGTM!

**Pull request merged**
